// This file serves as a registry of all available email templates
// It can be used by the EmailSenderAdmin to populate the template dropdown

const emailTemplateRegistry = [
  {
    id: "general",
    name: "General Information",
    category: "general",
    subject: "[Nkumba University] {{subject}}",
    description: "General purpose communication template",
    variables: [
      { name: "recipientName", label: "Recipient Name", required: true },
      { name: "subject", label: "Subject", required: true },
      { name: "message", label: "Message", required: true },
      { name: "ctaText", label: "Call to Action Text", required: false },
      { name: "ctaLink", label: "Call to Action Link", required: false },
    ],
  },
  {
    id: "admission",
    name: "Admission Letter",
    category: "academic",
    subject: "[Nkumba University] Admission Offer - {{program}}",
    description:
      "Used to notify applicants of their admission to the university",
    variables: [
      { name: "studentName", label: "Student Name", required: true },
      { name: "program", label: "Program Name", required: true },
      { name: "startDate", label: "Start Date", required: true },
      { name: "tuitionAmount", label: "Tuition Amount", required: true },
    ],
  },
  {
    id: "registration",
    name: "Semester Registration",
    category: "academic",
    subject: "[Nkumba University] Semester Registration Reminder",
    description: "Reminder for students to register for the upcoming semester",
    variables: [
      { name: "studentName", label: "Student Name", required: true },
      { name: "semester", label: "Semester", required: true },
      {
        name: "registrationDeadline",
        label: "Registration Deadline",
        required: true,
      },
    ],
  },
  {
    id: "exam",
    name: "Exam Notification",
    category: "academic",
    subject: "[Nkumba University] Examination Schedule - {{program}}",
    description: "Notification about upcoming examinations",
    variables: [
      { name: "studentName", label: "Student Name", required: true },
      { name: "program", label: "Program", required: true },
      { name: "examStartDate", label: "Exam Start Date", required: true },
      { name: "examEndDate", label: "Exam End Date", required: true },
    ],
  },
  {
    id: "grades",
    name: "Grade Release",
    category: "academic",
    subject: "[Nkumba University] {{semester}} Grades Released",
    description: "Notification that semester grades are available",
    variables: [
      { name: "studentName", label: "Student Name", required: true },
      { name: "semester", label: "Semester", required: true },
      { name: "releaseDate", label: "Release Date", required: true },
      { name: "appealDeadline", label: "Appeal Deadline", required: true },
    ],
  },
  {
    id: "tuition",
    name: "Tuition Reminder",
    category: "financial",
    subject: "[Nkumba University] Tuition Payment Reminder",
    description: "Reminder for tuition payment",
    variables: [
      { name: "studentName", label: "Student Name", required: true },
      { name: "dueAmount", label: "Amount Due", required: true },
      { name: "dueDate", label: "Due Date", required: true },
    ],
  },
  {
    id: "payment",
    name: "Payment Confirmation",
    category: "financial",
    subject: "[Nkumba University] Payment Confirmation",
    description: "Confirmation of received payment",
    variables: [
      { name: "studentName", label: "Student Name", required: true },
      { name: "paymentAmount", label: "Payment Amount", required: true },
      { name: "paymentDate", label: "Payment Date", required: true },
      { name: "remainingBalance", label: "Remaining Balance", required: true },
    ],
  },
  {
    id: "helpdesk",
    name: "Helpdesk Ticket",
    category: "support",
    subject: "[Nkumba University] Support Ticket Update - #{{ticketNumber}}",
    description: "Updates about support tickets",
    variables: [
      { name: "userName", label: "User Name", required: true },
      { name: "ticketNumber", label: "Ticket Number", required: true },
      { name: "ticketSubject", label: "Ticket Subject", required: true },
      { name: "ticketStatus", label: "Ticket Status", required: true },
    ],
  },
  {
    id: "event",
    name: "Event Invitation",
    category: "events",
    subject: "[Nkumba University] Invitation: {{eventName}}",
    description: "Invitation to university events",
    variables: [
      { name: "recipientName", label: "Recipient Name", required: true },
      { name: "eventName", label: "Event Name", required: true },
      { name: "eventDate", label: "Event Date", required: true },
      { name: "eventTime", label: "Event Time", required: true },
      { name: "eventLocation", label: "Event Location", required: true },
    ],
  },
  {
    id: "login",
    name: "Login Alert",
    category: "security",
    subject: "[Nkumba University] New Login to Your Account",
    description: "Security alert for new account logins",
    variables: [
      { name: "userName", label: "User Name", required: true },
      { name: "deviceType", label: "Device Type", required: true },
      { name: "loginTime", label: "Login Time", required: true },
      { name: "location", label: "Location", required: true },
    ],
  },
  {
    id: "otp",
    name: "OTP Verification",
    category: "security",
    subject: "[Nkumba University] Your Verification Code",
    description: "One-time password for account verification",
    variables: [
      { name: "userName", label: "User Name", required: true },
      { name: "otpCode", label: "OTP Code", required: true },
      { name: "expiryTime", label: "Expiry Time", required: true },
    ],
  },
  {
    id: "account",
    name: "Account Creation",
    category: "security",
    subject: "[Nkumba University] Your Account Has Been Created",
    description: "New account credentials notification",
    variables: [
      { name: "userName", label: "User Name", required: true },
      { name: "userId", label: "User ID", required: true },
      { name: "password", label: "Password", required: true },
    ],
  },
  {
    id: "password",
    name: "Password Reset",
    category: "security",
    subject: "[Nkumba University] Password Reset Request",
    description: "Instructions for resetting account password",
    variables: [
      { name: "userName", label: "User Name", required: true },
      { name: "resetLink", label: "Reset Link", required: true },
      { name: "expiryTime", label: "Expiry Time", required: true },
    ],
  },
  {
    id: "welcome",
    name: "Welcome Email",
    category: "general",
    subject: "[Nkumba University] Welcome to Nkumba University!",
    description: "Welcome message for new students",
    variables: [
      { name: "studentName", label: "Student Name", required: true },
      { name: "program", label: "Program", required: true },
      { name: "academicYear", label: "Academic Year", required: true },
      { name: "orientationDate", label: "Orientation Date", required: true },
    ],
  },
  {
    id: "maintenance",
    name: "System Maintenance",
    category: "general",
    subject: "[Nkumba University] Scheduled System Maintenance",
    description: "Notification about upcoming system maintenance",
    variables: [
      { name: "recipientName", label: "Recipient Name", required: true },
      { name: "maintenanceDate", label: "Maintenance Date", required: true },
      { name: "startTime", label: "Start Time", required: true },
      { name: "endTime", label: "End Time", required: true },
      { name: "affectedSystems", label: "Affected Systems", required: true },
    ],
  },
  {
    id: "birthday",
    name: "Birthday Greeting",
    category: "special",
    subject: "[Nkumba University] Happy Birthday!",
    description: "Birthday greetings for students and staff",
    variables: [
      { name: "recipientName", label: "Recipient Name", required: true },
    ],
  },
  {
    id: "gradclearence",
    name: "Graduation Clearence",
    category: "special",
    subject: "[Nkumba University] Graduation Clearence!",
    description: "Graduation Clearence for students and staff",
    variables: [
      { name: "recipientName", label: "Recipient Name", required: true },
    ],
  },
];

export default emailTemplateRegistry;
