export const initialCourses = [
  {
    key: "1",
    name: "Advanced Machine Learning",
    instructor: "Dr. Sarah Chen",
    category: "Technology",
    format: "hybrid",
    enrolled: 156,
    completionRate: 78,
    status: "Active",
    rating: 4.8,
    startDate: "2024-03-01",
    endDate: "2024-06-30",
    description: "Advanced concepts in machine learning and AI applications",
    color: "#1890ff",
    isPublic: true,
    certificateEnabled: true,
    enrollmentOpen: true,
  },
  {
    key: "2",
    name: "Strategic Leadership",
    instructor: "Prof. James Wilson",
    category: "Business",
    format: "online",
    enrolled: 89,
    completionRate: 62,
    status: "Active",
    rating: 4.5,
    startDate: "2024-03-15",
    endDate: "2024-05-15",
    description: "Leadership strategies for modern organizations",
    color: "#52c41a",
    isPublic: true,
    certificateEnabled: true,
    enrollmentOpen: true,
  },
  {
    key: "3",
    name: "Data Science & Analytics",
    instructor: "Dr. Michael Chang",
    category: "Technology",
    format: "online",
    enrolled: 203,
    completionRate: 85,
    status: "Active",
    rating: 4.9,
    startDate: "2024-04-01",
    endDate: "2024-07-31",
    description: "Comprehensive data science methodology and tools",
    color: "#722ed1",
    isPublic: true,
    certificateEnabled: true,
    enrollmentOpen: true,
  },
  {
    key: "4",
    name: "Digital Marketing Mastery",
    instructor: "Emma Roberts",
    category: "Marketing",
    format: "hybrid",
    enrolled: 175,
    completionRate: 71,
    status: "Upcoming",
    rating: 4.6,
    startDate: "2024-05-01",
    endDate: "2024-08-31",
    description: "Modern digital marketing strategies and implementation",
    color: "#faad14",
    isPublic: false,
    certificateEnabled: true,
    enrollmentOpen: false,
  },
];
